<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <script>
      // 1. 声明异步函数: async
      async function foo() {
        console.log(1);
      }
      foo();

      // 2. 异步函数的内部代码执行顺序与普通函数是一致的 默认情况下也会同步执行

      // 3. 异步函数的返回值:
      // 函数的返回值为 promise 对象
      // promise 对象的结果由 async 函数return的返回值决定
      const bar = async function () {
        // 1. 如果return的是非promise的任意值, 那么得到一个新的状态为fulfilled的promise, value为返回值
        //  return 520;

        // 2. 如果return是一个Promise对象，那么return的Promise对象的结果状态决定了新的Promise的结果状态
        return new Promise((resolve, reject) => {
          resolve("YES");
        });

        // 3. 如果抛出异常, 新 promise 变为 rejected
        //  在异步函数里面如果抛出了异常(产生了错误), 这个异常不会如普通函数一样立即被浏览器处理 ,
        //  而是会在异步函数中进行处理: Promise.reject(err)

        // "abc".filter();
        // throw new Error("asycn fun err");
      };

      bar()
        .then((res) => {
          console.log("res", res);
        })
        .catch((err) => {
          console.log("异步函数捕获异常:", err);
        });

      // 4. await关键字
      /*
        1. await 右侧的表达式一般为 promise 对象, 但也可以是其它的值
        2. 如果表达式是 promise 对象, await 返回的是 promise 成功的值
        3. 如果表达式是其它值, 直接将此值作为 await 的返回值
        4. await 必须写在 async 函数中, 但 async 函数中可以没有 await
        5. 如果 await 的 promise 失败了, 就会抛出异常, 需要通过 try...catch 捕获处理
        6. await会等待Promise得到结果之后才会继续执行后续代码
      */

      const baz = async () => {
        let p1 = new Promise((resolve, reject) => {
          setTimeout(() => {
            resolve("ok");
          }, 2000);
        });

        let p2 = new Promise((resolve, reject) => {
          reject("throw error");
        });
        //1. 右侧为promise的情况
        let baz1 = await p1;
        console.log(baz1);

        //2. 右侧为其他类型的数据
        let baz2 = await 20;
        console.log(baz2);

        //3. 如果promise是失败的状态
        try {
          let baz3 = await p2;
        } catch (err) {
          console.log(err);
        }
      };
      baz();

      // 5. async & await处理异步请求
      function request(url) {
        return new Promise((resolve, reject) => {
          setTimeout(() => {
            resolve(url);
          }, 2000);
        });
      }

     async function getData() {
        const res1 = await request("zgc");
        console.log("res1", res1);

        const res2 = await request(res1 + "wf");
        console.log("res2", res2);

        const res3 = await request(res2 + "wlc");
        console.log("res3", res3);
      }
      getData()
    </script>
  </body>
</html>
